### ISSUE TITLE
Numerous errors thrown when running db:odmRebase

### ISSUE THREAD

**Issue by nwlucas** [CleverStack/clever-countries#1]
https://gist.github.com/nwlucas/45abd1ba51feaf4da87d

The above gist shows numerous errors thrown when trying to use db:odmrebase after installing clever-countries(without errors)

The error on line 4:
{ var Module = require( 'classes' ).ModuleClass.extend({
                                                                          ^

goes away when changed to
{ var Module = require( 'classes' ).Module.extend({

After looking at the code in the lib folder this seemed to be the correct way to fix, based on the naming of the Module.js file. Is this correct?

That aside I'm still confused on the approach for the error listed on line 26

**Comment by pilsy** [comment]
I have started refactoring this module to support the node-seed 1.0.x, i will need a couple more days to finish this
